// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYuEDvvPnVrKj86OFkReo0DvDZKtiBzXU',
    appId: '1:832573395255:web:3a5c750a6b9f07ab674ab2',
    messagingSenderId: '832573395255',
    projectId: 'puzzle-9e8c6',
    authDomain: 'puzzle-9e8c6.firebaseapp.com',
    storageBucket: 'puzzle-9e8c6.appspot.com',
    measurementId: 'G-WQ1KXH9X3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChytJaGY4SZTdnVUAt5jy-ntTUkcDFIVE',
    appId: '1:832573395255:android:864434fc3e9f1b83674ab2',
    messagingSenderId: '832573395255',
    projectId: 'puzzle-9e8c6',
    storageBucket: 'puzzle-9e8c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-nC8EcbCCniVTJLU6SKZhmkVU-6wW1o',
    appId: '1:832573395255:ios:97d9a6e83199e068674ab2',
    messagingSenderId: '832573395255',
    projectId: 'puzzle-9e8c6',
    storageBucket: 'puzzle-9e8c6.appspot.com',
    iosBundleId: 'com.example.puzzle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV-nC8EcbCCniVTJLU6SKZhmkVU-6wW1o',
    appId: '1:832573395255:ios:97d9a6e83199e068674ab2',
    messagingSenderId: '832573395255',
    projectId: 'puzzle-9e8c6',
    storageBucket: 'puzzle-9e8c6.appspot.com',
    iosBundleId: 'com.example.puzzle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYuEDvvPnVrKj86OFkReo0DvDZKtiBzXU',
    appId: '1:832573395255:web:964402ccbdf5406a674ab2',
    messagingSenderId: '832573395255',
    projectId: 'puzzle-9e8c6',
    authDomain: 'puzzle-9e8c6.firebaseapp.com',
    storageBucket: 'puzzle-9e8c6.appspot.com',
    measurementId: 'G-6PTZ0YFYZK',
  );
}
